var arr=[
  {
    openId: 0,
    "nickName": "越花儿",
    "sign": "个性签名",
    "phone": "13546117895",
    "avatarUrl": "../../images/headportrait/孙膑.jpg",
    "sex": "男",
    "wx": "wx号:zyhchixiangjiao",
    "birthday": null,
    "location": "武汉",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "赵红没香蕉",
    "job": "工作",
    "like": false,
    "schoolName": "HUST",
    "startYear": "2017",
    "description": "已关注",
    "relationship": 1
  },
  {
    openId: 1,
    "nickName": "艺姐",
    "sign": "个性签名",
    "phone": "13948726191",
    "avatarUrl": "../../images/headportrait/花木兰.jpg" ,
    "sex": "女",
    "wx": "wx号:zyzizi",
    "birthday": null,
    "location": "Singapore",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "密室逃脱",
    "job": "工作",
    "like": false,
    "schoolName": "OXFORD",
    "startYear": "2019",
    "description": "已关注",
    "relationship": 2
  },
  {
    openId: 2,
    "nickName": "DOGO",
    "sign": "个性签名",
    "phone": "18022849377",
    "avatarUrl": "../../images/headportrait/露娜.jpg",
    "sex": "女",
    "wx": "wx号:dogodogo",
    "birthday": null,
    "location": "北京",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "张宇轩（小学）",
    "job": "工作",
    "like": false,
    "schoolName": "THU",
    "startYear": "2017",
    "description": "已关注",
    "relationship": 2
  },
  {
    openId: 3,
    "nickName": "茄茄",
    "sign": "个性签名",
    "phone": "13823901994",
    "avatarUrl": "../../images/headportrait/诸葛亮.jpg",
    "sex": "男",
    "wx": "wx号:wjxbuchiqiezi",
    "birthday": null,
    "location": "上海",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "进四大进投行",
    "job": "工作",
    "like": false,
    "schoolName": "SUFE",
    "startYear": "2017",
    "description": "关注",
    "relationship": 3
  },
  {
    openId: 4,
    "nickName": "边边",
    "sign": "个性签名",
    "phone": "18830024892",
    "avatarUrl": "../../images/headportrait/周瑜.jpg",
    "sex": "男",
    "wx": "wx号:mjycaishidahaoren",
    "birthday": null,
    "location": "北京",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "花半个小时改数据",
    "job": "工作",
    "like": false,
    "schoolName": "BUPT",
    "startYear": "2017",
    "description": "已关注",
    "relationship":2
  },
  {
    openId: 5,
    "nickName": "萌萌",
    "sign": "个性签名",
    "phone": "18728490203",
    "avatarUrl": "../../images/headportrait/安琪拉.jpg",
    "sex": "女",
    "wx": "wx号:balabala",
    "birthday": null,
    "location": "北京",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "我不会挂科",
    "job": "工作",
    "like": false,
    "schoolName": "BUPT",
    "startYear": "2017",
    "description": "关注",
    "relationship": 3
  },
  {
    openId: 6,
    "nickName": "君哥",
    "sign": "个性签名",
    "phone": "15829439281",
    "avatarUrl": "../../images/headportrait/小乔.jpg",
    "sex": "女",
    "wx": "wx号:juju",
    "birthday": null,
    "location": "上海",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "柴柴不是哈士奇",
    "job": "工作",
    "like": false,
    "schoolName": "SJTU",
    "startYear": "2017",
    "description": "已关注",
    "relationship": 1
  },
  {
    openId: 7,
    "nickName": "穆丝Gao",
    "sign": "个性签名",
    "phone": "18923040023",
    "avatarUrl": "../../images/headportrait/孙悟空.jpg",
    "sex": "男",
    "wx": "wx号:musssssss",
    "birthday": null,
    "location": "武汉",
    "hometown": "郑州",
    "company": "公司",
    "favorite": "unknown",
    "job": "工作",
    "like": false,
    "schoolName": "WHU",
    "startYear": "2017",
    "description": "已关注",
    "relationship": 2
  }
  
]

module.exports={arr:arr}